# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Hardware-Vhdl-Tidy
version:      0.8
version_from: lib/Hardware/Vhdl/Tidy.pm
installdirs:  site
requires:
    Carp:                          0
    Exporter:                      0
    Getopt::Long:                  0
    Hardware::Vhdl::Lexer:         1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
